### ISSUE TITLE
A single place to download them all

### ISSUE THREAD

**Issue by alkino** [DEShawResearch/random123#4]
Hello,
It would be nice to have a single place to download all versions.

In this place https://www.deshawresearch.com/downloads/download_random123.cgi/ we cannot find the last version.

And on github we cannot download previous version.

It would be nice to "fake" the history here, to have a tag for each version.

Regards

**Comment by fennm** [comment]
FWIW, added 1.14.0 to https://www.deshawresearch.com/downloads/download_random123.cgi/, so you can now download all releases in the same place.

**Comment by alkino** [comment]
It does not fix the problem I was underlying (sorry for not being clear).
Some downloader as [spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/random123/package.py), automatically build download link from url by replacing version number. It is not possible if the url change.
The easiest way will be to fake history here.
I can try a PR for that if you want.

**Comment by fennm** [comment]
Im not sure I understand the issue after reviewing the spack package:  it seems like you’ve already handled the case where old versions (which will not change) have specific URLs which differ from the pattern used in the new version.  Perhaps it would be useful for you to post a patch showing what you’d like the package.py to look like?

While faking the history using the release tars isn’t technically difficult, I don’t think that is good option here because it’s not possible for the main branch to reflect the true history at this point. Having a forest of unconnected branches/tags seems like it’ll be a source of confusion down the line.

**Comment by fennm** [comment]
Closing #4 but feel free to open a new issue if the current spack package.py isn't an acceptable solution.

**Comment by alkino** [comment]
As you can see here: https://github.com/BlueBrain/Random123/releases

It is possible.
And not a so ugly history: https://github.com/BlueBrain/Random123/commits/master (go to the bottom)
